package raf.dsw.gerumap.message;

public enum EventType {
    DODATO_DETE_ELEMENTU,
    OBRISAN_EXPLORER,
    PRAZNO_IME,
    NIJE_SELEKTOVAN_CVOR,
    NIJE_SELEKTOVAN_POJAM,
    PREKLAPANJE_POJMA,
    VEZA_NIJE_DOVRSENA,
    IZABRANA_BOJA,
    NIJE_IZABRAN_PROJEKAT,
    IZABRATI_EXPLORER,
    NIJE_IZABRANA_MAPA,
    MAPA_DODATA_KAO_PATTERN
}
